import React, { useState } from "react";
import './components.css';
import myImage from '../assets/planet-jupiter.svg';
import internalImage from '../assets/planet-jupiter-internal.svg';
import surfaceImage from '../assets/geology-jupiter.png';
import { Link } from "react-router-dom";

function Mars () {

  const originalPlanetinfo = {
    name: "Jupiter",
    image: myImage,
    information: 'Jupiter is the fifth planet from the Sun and the largest in the solar system. It is a gas giant composed mostly of hydrogen and helium, with a dense core surrounded by thick layers of gas and clouds. Its atmosphere features the Great Red Spot, a massive storm. Jupiter has at least 79 moons, including Ganymede, the largest moon in the solar system. It also has a powerful magnetic field and a ring system, though faint.',
    internalStructure: 'Jupiter\'s core is likely made of rock and ice, surrounded by a layer of metallic hydrogen, which forms due to extreme pressure. The outer layers are mostly composed of hydrogen and helium in gaseous form, with a thick atmosphere of clouds. Jupiter has a strong magnetic field generated by its liquid metallic hydrogen core. This magnetic field is about 14 times stronger than Earth\’s and extends far beyond the planet itself.',
    surfaceGeology: 'Being a gas giant, Jupiter does not have a solid surface like Earth. Instead, it has a dense atmosphere composed of clouds of hydrogen, helium, and ammonia, with turbulent storms and high-pressure systems. Jupiter\'s atmosphere is constantly shifting, with powerful jet streams creating bands of clouds that circle the planet at different speeds. These cloud bands are distinct in color, due to different chemical compositions and temperatures in the atmosphere.'
  }

  const [planetInfo, setPlanetInfo] = useState(originalPlanetinfo)

  const handleButtonClick = (type) => {
   switch (type) {
    case 'overview': setPlanetInfo(originalPlanetinfo);
    break;
    case 'internal': setPlanetInfo({
      ...planetInfo,
      information: planetInfo.internalStructure,
      image: internalImage
    });
    break;
    case 'surface': setPlanetInfo({
      ...planetInfo,
      information: planetInfo.surfaceGeology,
      image: surfaceImage
    });
    break;
    default:
      break;
   } 
  }

    return (
        <div className="planet-content">

          <div className="main">
            <div className="image">
              <img src={planetInfo.image} alt="Mercury"></img>
            </div>

            <div className="info">
              <div className="planet-title">{planetInfo.name}</div>
              <div className="information">{planetInfo.information}</div>

              <div className="source">Source: <a href="https://www.wikipedia.org" target="_blank" rel="noopener noreferrer">Wikipediaʔ</a></div>

              <div className="button"><Link className="btn btn-custom" onClick={() => handleButtonClick('overview')}>1. Overview</Link></div>
              <div className="button"><Link className="btn btn-custom" onClick={() => handleButtonClick('internal')}>2. Internal Structure</Link></div>
              <div className="button"><Link className="btn btn-custom" onClick={() => handleButtonClick('surface')} >3. Surface Geology</Link></div>
            </div>
          </div>

          <div className="footer">
              <div className="box">
                <div className="title">rotation time</div>
                <div className="content">9.93 hours</div>
              </div>
              <div className="box">
                <div className="title">revolution time</div>
                <div className="content">11.86 years</div>
              </div>
              <div className="box">
                <div className="title">radius</div>
                <div className="content">69,911 km</div>
              </div>
              <div className="box">
                <div className="title">average temp</div>
                <div className="content">-108°C</div>
              </div>
          </div>
        </div>
    );
}

export default Mars;