import React, { useEffect, useState } from "react";
import './components.css';
import myImage from '../assets/planet-neptune.svg';
import internalImage from '../assets/planet-neptune-internal.svg';
import surfaceImage from '../assets/geology-neptune.png';
import { Link } from "react-router-dom";

function Neptune () {

  const originalPlanetinfo = {
    name: "Neptune",
    image: myImage,
    internalImage: internalImage,
    surfaceImage: surfaceImage,
    information: 'Neptune is the eighth and farthest planet from the Sun. It is an ice giant, composed mostly of hydrogen, helium, and ices like water, ammonia, and methane. Neptune is known for its deep blue color, which is caused by methane in its atmosphere, and for having the strongest winds of any planet in the solar system.',
    internalStructure: 'Neptune has a small, dense core made of rock and metal, surrounded by a thick layer of ices and gases. The planet’s atmosphere consists primarily of hydrogen, helium, and methane. Neptune’s internal heat is relatively high compared to Uranus, likely due to residual heat from its formation and possible ongoing contraction. It has a strong magnetic field, generated by the movement of conductive materials in its interior.',
    surfaceGeology: 'Neptune has no solid surface, with a thick atmosphere made of hydrogen, helium, and methane. It features visible storm systems, such as the Great Dark Spot, which is similar to Jupiter\'s Great Red Spot. Neptune also experiences extreme weather conditions, including the fastest winds in the solar system, which can reach speeds of over 2,000 km/h.'
  }

  const [planetInfo, setPlanetInfo] = useState(originalPlanetinfo)

  const handleButtonClick = (type) => {
   switch (type) {
    case 'overview': setPlanetInfo(originalPlanetinfo);
    break;
    case 'internal': setPlanetInfo({
      ...planetInfo,
      information: planetInfo.internalStructure,
      image: internalImage
    });
    break;
    case 'surface': setPlanetInfo({
      ...planetInfo,
      information: planetInfo.surfaceGeology,
      image: surfaceImage
    });
    break;
    default:
      break;
   } 
  }

    return (
        <div className="planet-content">

          <div className="main">
            <div className="image">
              <img src={planetInfo.image} alt="Mercury"></img>
            </div>

            <div className="info">
              <div className="planet-title">{planetInfo.name}</div>
              <div className="information">{planetInfo.information}</div>

              <div className="source">Source: <a href="https://www.wikipedia.org" target="_blank" rel="noopener noreferrer">Wikipediaʔ</a></div>

              <div className="button"><Link className="btn btn-custom" onClick={() => handleButtonClick('overview')}>1. Overview</Link></div>
              <div className="button"><Link className="btn btn-custom" onClick={() => handleButtonClick('internal')}>2. Internal Structure</Link></div>
              <div className="button"><Link className="btn btn-custom" onClick={() => handleButtonClick('surface')} >3. Surface Geology</Link></div>
            </div>
          </div>

          <div className="footer">
              <div className="box">
                <div className="title">rotation time</div>
                <div className="content">16.08 hours</div>
              </div>
              <div className="box">
                <div className="title">revolution time</div>
                <div className="content">164.79 years</div>
              </div>
              <div className="box">
                <div className="title">radius</div>
                <div className="content">24,622 km</div>
              </div>
              <div className="box">
                <div className="title">average temp</div>
                <div className="content">-201°C</div>
              </div>
          </div>
        </div>
    );
}

export default Neptune;