import React, { useState } from "react";
import './components.css';
import myImage from '../assets/planet-saturn.svg';
import internalImage from '../assets/planet-saturn-internal.svg';
import surfaceImage from '../assets/geology-saturn.png';
import { Link } from "react-router-dom";

function Saturn () {

  const originalPlanetinfo = {
    name: "Saturn",
    image: myImage,
    information: 'Saturn is the sixth planet from the Sun and is famous for its stunning ring system, made of ice, rock, and dust particles. It is a gas giant composed mainly of hydrogen and helium, similar to Jupiter. Saturn has at least 82 moons, with Titan being the largest. Titan is notable for having a thick atmosphere and lakes of liquid methane.',
    surfaceGeology: 'Saturn doesn\'t have a solid surface. Its atmosphere consists of layers of clouds, storms, and high-speed winds, with a faint ring system made up of ice and rock particles. Saturn\’s atmosphere is known for its low density, and it has large, long-lasting storms like the Great White Spot, which occurs periodically.',
    internalStructure: 'Saturn has a rocky core surrounded by a thick layer of metallic hydrogen, followed by gaseous hydrogen and helium. The core is likely composed of iron, nickel, and silicates. Saturn’s outer atmosphere is primarily made up of hydrogen and helium, and it has a strong magnetic field generated by the metallic hydrogen layer. Despite its large size, Saturn has the lowest density of any planet in the solar system, meaning it could float in water if there were a body of water large enough.'
  }

  const [planetInfo, setPlanetInfo] = useState(originalPlanetinfo)

  const handleButtonClick = (type) => {
   switch (type) {
    case 'overview': setPlanetInfo(originalPlanetinfo);
    break;
    case 'internal': setPlanetInfo({
      ...planetInfo,
      information: planetInfo.internalStructure,
      image: internalImage
    });
    break;
    case 'surface': setPlanetInfo({
      ...planetInfo,
      information: planetInfo.surfaceGeology,
      image: surfaceImage
    });
    break;
    default:
      break;
   } 
  }

    return (
        <div className="planet-content">

          <div className="main">
            <div className="image">
              <img src={planetInfo.image} alt="Mercury"></img>
            </div>

            <div className="info">
              <div className="planet-title">{planetInfo.name}</div>
              <div className="information">{planetInfo.information}</div>

              <div className="source">Source: <a href="https://www.wikipedia.org" target="_blank" rel="noopener noreferrer">Wikipediaʔ</a></div>

              <div className="button"><Link className="btn btn-custom" onClick={() => handleButtonClick('overview')}>1. Overview</Link></div>
              <div className="button"><Link className="btn btn-custom" onClick={() => handleButtonClick('internal')}>2. Internal Structure</Link></div>
              <div className="button"><Link className="btn btn-custom" onClick={() => handleButtonClick('surface')} >3. Surface Geology</Link></div>
            </div>
          </div>

          <div className="footer">
              <div className="box">
                <div className="title">rotation time</div>
                <div className="content">10.8 days</div>
              </div>
              <div className="box">
                <div className="title">revolution time</div>
                <div className="content">29.46 years</div>
              </div>
              <div className="box">
                <div className="title">radius</div>
                <div className="content">58,232 km</div>
              </div>
              <div className="box">
                <div className="title">average temp</div>
                <div className="content">-138°C</div>
              </div>
          </div>
        </div>
    );
}

export default Saturn;